/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Find;

import Database.*;
import static Database.Database.loadImageIcon;
import Home.Profile;
import User.User;
import calender.calender;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.*;

/**
 *
 * @author user
 */
public class FindYourPatner extends javax.swing.JFrame {
    private String userName;
    private JPanel listPanel;

   
    public FindYourPatner() {
        initComponents();
          
    }
    
    public FindYourPatner(String userName) {
        this.userName = userName; // Simpan nama pengguna
        initComponents();
         // Inisialisasi listPanel setelah komponen diinit
        listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        list_scrollpanel.setViewportView(listPanel); // Menyambungkan listPanel ke list_scrollpanel
        
        // Memuat data pengguna setelah semua komponen siap
        loadUserData();
       label_nama.setText("Hello, " + userName); // Tampilkan nama pengguna di halaman
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_profile = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_calender = new javax.swing.JButton();
        btn_logOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        list_scrollpanel = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 178, 185));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel1.setText("SoulMate.");

        btn_profile.setText("Profile");
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_find.setText("Find Your Patner");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        btn_calender.setText("Calender");
        btn_calender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calenderActionPerformed(evt);
            }
        });

        btn_logOut.setText("Log Out");
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/11zon_resized (7).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calender, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_find)
                    .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_calender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(btn_logOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        list_scrollpanel.setBackground(new java.awt.Color(239, 178, 185));
        list_scrollpanel.setForeground(new java.awt.Color(239, 178, 185));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Find Your Patner");

        label_nama.setForeground(new java.awt.Color(204, 204, 204));
        label_nama.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(list_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
     Profile ProfileFrame = new Profile();
        ProfileFrame.setVisible(true);
        ProfileFrame.pack();
        ProfileFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
      FindYourPatner findFrame = new FindYourPatner();
        findFrame.setVisible(true);
        findFrame.pack();
        findFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_calenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calenderActionPerformed
        calender calendarFrame = new calender(userName); // Kirim nama pengguna
        calendarFrame.setVisible(true);
        this.dispose(); // Tutup halaman saat ini
    }//GEN-LAST:event_btn_calenderActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logOutActionPerformed

private void loadUserData() {
    List<User> users = Database.getAllUsers();
    if (users == null || users.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tidak ada data pengguna ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    for (User user : users) {
        // Panel utama untuk setiap pengguna
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout(10, 10)); // BorderLayout dengan jarak antar elemen
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.LIGHT_GRAY)); // Garis pemisah di bawah

        // Panel untuk gambar pengguna
        JLabel imageLabel = new JLabel();
        ImageIcon userImage = loadImageIcon(user.getEmail()); // Ambil gambar berdasarkan email
        if (userImage != null) {
            Image img = userImage.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); // Ukuran gambar lebih besar
            imageLabel.setIcon(new ImageIcon(img));
        } else {
            imageLabel.setText("No Image"); // Placeholder jika tidak ada gambar
        }

        // Panel detail pengguna
        JPanel detailPanel = new JPanel();
        detailPanel.setLayout(new BoxLayout(detailPanel, BoxLayout.Y_AXIS));
        detailPanel.setBackground(Color.WHITE);

        // Tambahkan nama pengguna di dalam detail
        JLabel labelName = new JLabel(user.getName()); // Nama pengguna
        labelName.setFont(new Font("Arial", Font.BOLD, 14)); // Nama lebih besar dan bold
        labelName.setForeground(new Color(50, 50, 50)); // Warna teks lebih gelap

        JLabel labelNpm = new JLabel("NPM: " + user.getNpm());
        JLabel labelFaculty = new JLabel("Fakultas: " + user.getFaculty());
        JLabel labelProgram = new JLabel("Program Studi: " + user.getProgram());

        // Menyesuaikan font dan warna untuk detail lainnya
        labelNpm.setFont(new Font("Arial", Font.PLAIN, 12));
        labelFaculty.setFont(new Font("Arial", Font.PLAIN, 12));
        labelProgram.setFont(new Font("Arial", Font.PLAIN, 12));

        // Tambahkan komponen ke detail panel
        detailPanel.add(labelName); // Tambahkan nama pengguna terlebih dahulu
        detailPanel.add(labelNpm);
        detailPanel.add(labelFaculty);
        detailPanel.add(labelProgram);

        // Tambahkan tombol "Get to know" di kanan
        JButton chatButton = new JButton("Get to know");
        chatButton.setBackground(new Color(0, 150, 255)); // Warna biru
        chatButton.setForeground(Color.WHITE);
        chatButton.setFont(new Font("Arial", Font.BOLD, 14));
        chatButton.setFocusPainted(false);
        chatButton.addActionListener(e -> openLink(user.getLink())); // Tambahkan listener untuk membuka link

        // Panel untuk menempatkan tombol di sisi kanan
        JPanel buttonPanel = new JPanel(new BorderLayout());
        buttonPanel.setBackground(Color.WHITE);
        buttonPanel.add(chatButton, BorderLayout.NORTH); // Letakkan di bagian atas agar sejajar

        // Tambahkan elemen ke panel utama
        panel.add(imageLabel, BorderLayout.WEST); // Gambar di kiri
        panel.add(detailPanel, BorderLayout.CENTER); // Detail pengguna di tengah
        panel.add(buttonPanel, BorderLayout.EAST); // Tombol di kanan

        listPanel.add(panel); // Tambahkan ke listPanel
    }

    listPanel.revalidate();
    listPanel.repaint();
}




private void openLink(String link) {
    if (link == null || link.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Link tidak tersedia!", "Informasi", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Desktop desktop = Desktop.getDesktop();
        if (desktop.isSupported(Desktop.Action.BROWSE)) {
            desktop.browse(new java.net.URI(link));
        } else {
            JOptionPane.showMessageDialog(this, "Fitur browsing tidak didukung pada sistem ini.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Gagal membuka link: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}





  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindYourPatner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindYourPatner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindYourPatner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindYourPatner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindYourPatner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calender;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JButton btn_profile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_nama;
    private javax.swing.JScrollPane list_scrollpanel;
    // End of variables declaration//GEN-END:variables
}
